### ISSUE TITLE
Libqrcode does not support Windows

### ISSUE THREAD

**Issue by Beletre** [yax-lakam-tuun/libqrcode#2]
:(

**Comment by yax-lakam-tuun** [comment]
There is not enough C++20 support from _MSVC_ yet.
I will setup a _Windows_ container which is able to build the project but until _Microsoft_ adds further C++20 support, it won't work.

**Comment by yax-lakam-tuun** [comment]
Windows is now supported. Please see https://github.com/yax-lakam-tuun/libqrcode/pull/7 for more info.
